# SPDX-FileCopyrightText: 2025 wallet-backend-reference
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".github/pull_request_template.md",
  "renovate.json",
  "CHANGELOG.md",
 "docs/DEVELOPMENT.md",
  "jreleaser.yml",
  ".mvn/settings.xml",
  "**/*/pmd_default_java.xml",
  "README.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 diggsweden/wallet-backend-reference"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]

path = [
    "**/*/eclipse-java-google-style.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "google/styleguide"
SPDX-License-Identifier = "CC-BY-3.0"


[[annotations]]
path = [
    "**/*/google_checks.xml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "checkstyle/checkstyle"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "mvnw",
    "mvnw.cmd",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Apache Software Foundation (ASF)"
SPDX-License-Identifier = "Apache-2.0"